### ISSUE TITLE
Lastest update problems

### ISSUE THREAD

**Issue by cyberlimbo** [TeaSpeak/TeaClient#40] opened 2020-10-05 00:16 UTC
Some of the last update problems.
TeaSpeak Client v1.4.12

1. TeaSpeak client is starting very slow (animations are really slow and boring)
2. TeaSpeak client Microphone settings problems (I removed "Enable RNNoise cancelation" option 
and the next time i started teaspeak client, RNNoise cancelation it is activated again)
3. TeaSpeak client Sound problems (sometimes the users "blue lights" stays on and i stop listening everybody until i restart the client) 
4. "Failed to open preview" error (when clicking in a youtube link published in the channel, for example)

**Comment by WolverinDEV** [comment] 2020-10-05 08:31
Hey,
thanks for the feedback.
First of all 1) will not change. It's the Halloween animation and it'll stay 'till 5.11.
May I add a "loader abort" option in the settings, but I'll have to take a look.

2) I can't reproduce that. If I turn off that option, it stays off, even though restarts^^
I'm also not sure what could even cause this issue, but does the client may not have write rights to AppData?
Seems like it fails to store settings (may try to change something else as well and take a look if that's getting saved)

3) I think I know what you're talking about.
For some reason, (on Windows) if you're changing the system sound volume, the audio playback hangs up.
This issue seems only be related to the MME driver. A driver like DirectSound works fine.

4) Yeahr...

**Comment by WolverinDEV** [comment] 2020-10-05 08:55
3) Well this isn't even reliable.
Even though using MME will not constantly cause this behaviour.

2) I may think I know what you mean.
You don't mean the indicator in the settings right?
It seems like the initial state is set to on and the setting itself is ignored.
Toggling the setting will update that flag and enable/disable rnnoise right?

**Comment by WolverinDEV** [comment] 2020-10-05 12:56
Update:
1) There is now a registry setting called `loader_animation_abort`
2) I've reproduced it and it shall be fixed in 1.4.13 (it affected all settings...)
4) Fixed in 1.4.13 as well..

Any other known bugs?

**Comment by cyberlimbo** [comment] 2020-10-05 16:57
> Update:
> 
> 1. There is now a registry setting called `loader_animation_abort`
> 2. I've reproduced it and it shall be fixed in 1.4.13 (it affected all settings...)
> 3. Fixed in 1.4.13 as well..
> 
> Any other known bugs?

Hi
Ok, i'll update my client and keep testing.
If there is more bugs, i'll report it.
You can close this thread ;)

**Closed as completed** 2020-10-05 18:54 UTC
